export default {
    daysHighlight: null,
    daysSelected: null,
    defaultDate: null,
    disableDates: null,
    disableDaysOfWeek: null,
    disablePastDays: false,
    format: 'DD/MM/YYYY',
    lang: 'en',
    langFolder: './dist/langs/',
    locked: false,
    maxDate: null,
    minDate: null,
    monthShort: false,
    multiplePick: false,
    nav: ['◀', '▶'],
    range: false,
    rtl: false,
    selector: '.hello-week',
    todayHighlight: true,
    weekShort: true,
    weekStart: 0,
    onLoad: () => { /** callback function */ },
    onClear: () => { /** callback function */ },
    onNavigation: () => { /** callback function */ },
    onSelect: () => { /** callback function */ },
};
