export declare function isDef(val: any): boolean;
export declare function isTrue(val: boolean): boolean;
export declare function isFalse(val: boolean): boolean;
export declare function isObject(obj: any): boolean;
export declare function isArray(obj: any): boolean;
export declare function isFuncation(func: any): boolean;
export declare function isString(val: string): boolean;
export declare function toArray(obj: any): unknown[];
export declare function isNode(arg: any): any;
